### ISSUE TITLE
Compatibility with suspend functions

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [haroldadmin/NetworkResponseAdapter#2]
At this moment the library is working with deferred and normal functions but if you try to use the new Retrofit support for suspend functions without the deferred wrapper it is not working.

**Comment by haroldadmin** [comment]
Thanks for bringing this up. I'll work on adding support for suspending functions for the next release.

**Comment by haroldadmin** [comment]
Support added via [this PR](https://github.com/haroldadmin/NetworkResponseAdapter/pull/3). This will be released as a 3.0 release, because there are some potentially breaking changes in the API.

`CoroutinesNetworkResponseAdapter` and `CoroutinesNetworkResponseAdapterFactory` classes have been deprecated, and replaced with `NetworkResponseAdapter` and `NetworkResponseAdapterFactory` classes.
