### ISSUE TITLE
Publish kdocs on gh-pages or some other site

### ISSUE THREAD

**Issue by simonsickle** [haroldadmin/NetworkResponseAdapter#22]
As a user of the library, I would like to see all of the documentation in an easy place such as github pages. This would allow me to see things not documented in the readme like the awesome support for backoff retries in the network response.

Since the library is open source, github actions could be used to do this automatically on push

**Comment by haroldadmin** [comment]
Excellent idea! I will try to setup a small documentation website today. I refrained from creating one earlier because the README contains basically all the information you need to know.

Having a website with docs, usage examples, and API reference would be awesome. I'll try to put something together over the weekend. No ETA though.

**Comment by haroldadmin** [comment]
Project documentation is now available at https://haroldadmin.github.io/NetworkResponseAdapter/

**Comment by simonsickle** [comment]
Thanks for this! I truly appreciate you doing this and the docs look awesome!
