### ISSUE TITLE
moshi exception incorrectly classified as network error

### ISSUE THREAD

**Issue by ninovanhooff** [haroldadmin/NetworkResponseAdapter#40]
When using mosh to parse invalid json, a com.squareup.moshi.JsonEncodingException might be produced. 

Contrary to the readme and documentation, this is wrapped in a NetworkResponse.NetworkError rather than an UnknownError

Either update the docs or the code, but at least make clear what we can expect ;-)

**Comment by haroldadmin** [comment]
Hi, thanks for reporting this. There is [logic in the library](https://github.com/haroldadmin/NetworkResponseAdapter/blob/16cc117af105d916d048e145677a0e687a52e461/src/main/kotlin/com/haroldadmin/cnradapter/ResponseHandler.kt#L59) to catch unknown exceptions such as the ones produced during JSON deserialization.

Since that check doesn't handle the error in your case, would it be possible for you to post a stack trace or a link to a sample project that can reproduce this error?

**Comment by haroldadmin** [comment]
Closing this due to a lack of response. Feel free to re-open if you continue to have this problem.
