### ISSUE TITLE
When expression with Success and Error is not exhaustive

### ISSUE THREAD

**Issue by argenkiwi** [haroldadmin/NetworkResponseAdapter#46]
With the current implementation of `NetworkResponse`, the following expression would not compile:
```
fun isSuccess(networkResponse: NetworkResponse<*, *>) = when (networkResponse) {
    is NetworkResponse.Success -> true
    is NetworkResponse.Error -> false
}
```
If `NetworkResponse` was a sealed interface and `Error` was also a sealed interface that implemented `NetworkResponse`, the above expression would compile. I'd be happy to submit a pull request for this adjustment if I was accepted as a contributor.

**Comment by haroldadmin** [comment]
Thank you for the suggestion. Issue #34 describes (amongst other things) the plan for this library to move to sealed interfaces so this is definitely on the list of improvements we can make. 

You're right, the code snippet you provided won't compile because the `when` expression is not exhaustive. I'm not sure if converting to sealed interface would be a breaking change for users of the current version of the library, so I'm not keen on pushing these changes to v4. 

I would gladly accept a PR for this on the `v5` branch.

**Comment by argenkiwi** [comment]
Sure, I can submit the pull request to the v5 branch if you have any concerns about backwards compatibility. The only requirement should be to Kotlin 1.5 to support sealed interfaces. I wouldn't expect any issues otherwise.

**Comment by haroldadmin** [comment]
Thanks! Looking forward to reviewing the PR.

**Comment by haroldadmin** [comment]
Closing with #47
