### ISSUE TITLE
Unable to caught Json parsing Error

### ISSUE THREAD

**Issue by anupdey99** [haroldadmin/NetworkResponseAdapter#7]
val response = repository.getReportById(id)
            val x = when(response) {
                is NetworkResponse.Success -> {
                    liveData.postValue(response.body)
                     //Json parsing Error not called here
                }
                is NetworkResponse.ServerError -> {
                    //Json parsing Error not called here
                }
                is NetworkResponse.NetworkError -> {
                     //Json parsing Error not called here
                }
            }

How to caught Json parsing Error if happens.

**Comment by haroldadmin** [comment]
Hi, I am assuming you're using the 3.x version of the library. This issue was recently brought up in #6.

What ends up happening is that the JSON parsing exceptions are swallowed, and never returned as a `NetworkResponse` subclass. To fix it, there were some breaking changes made in [4.0.0-alpha01](https://github.com/haroldadmin/NetworkResponseAdapter/releases/tag/4.0.0-alpha01). A new subclass of  `NetworkResponse` has been introduced by the name of `UnknownError`. This class is supposed to handle all other kinds of errors which can not be represented as a Server Error or a Network Error.

If you weren't using the 4.x release before, you might want to try it and see if it helps.

**Comment by anupdey99** [comment]
Yes, you are right. I am using "3.0.1" version. Thanks for quick response and good work! :)

**Comment by haroldadmin** [comment]
No worries. The fix hasn't been merged to master yet. I want to wait a little more while before creating a new release with breaking changes.

**Comment by anupdey99** [comment]
When can we accept new release?

**Comment by haroldadmin** [comment]
Just released the new version. See the release tag [here](https://github.com/haroldadmin/NetworkResponseAdapter/releases/tag/4.0.0). It should be available on Jitpack within a few mins if everything goes well.
